### ISSUE TITLE
Configuration -> Permissions scrolling is broken

### ISSUE THREAD

**Issue by daviddeutsch** [marcobarbosa/minima#12]
I cannot scroll beyond the detachable header, it somehow breaks and pulls me up again

**Comment by daviddeutsch** [comment]
(this is in FF3.6 btw)

**Comment by marcobarbosa** [comment]
This is fixed in the last commit. Could you try again and let me know please?

**Comment by daviddeutsch** [comment]
I was testing this on the demo, where it's apparently still an issue.

**Comment by marcobarbosa** [comment]
just updated the demo, can you try again?

**Comment by daviddeutsch** [comment]
nope, still the same

**Comment by marcobarbosa** [comment]
what's your resolution?

**Comment by daviddeutsch** [comment]
1920x1200px

**Comment by marcobarbosa** [comment]
Hey David, this should be fixed now, right? RIGHT? :o

**Comment by daviddeutsch** [comment]
butter smooth. ;-)
