### ISSUE TITLE
Username, Logout button, etc. are misplaced when JAT3 plugin is installed

### ISSUE THREAD

**Issue by blesswinsamuel** [marcobarbosa/minima#39]
I love the minima template. But when I installed and enabled the JAT3 Framefork plugin the Username, Private messages count, and Logout button are misplaced.
Here is the link for JAT3 Framefork plugin: http://www.joomlart.com/forums/downloads.php?do=file&id=2089
Here is the screenshot:
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/856/clipboardertemp266c2a.png/'><img src='http://img856.imageshack.us/img856/3462/clipboardertemp266c2a.png' border='0'/></a>

**Comment by marcobarbosa** [comment]
Fixed this here:
https://github.com/marcobarbosa/minima/commit/5254d3cc3c3f74a65fc3fef0bc211ba253a55d06

This fix is coming in the next release.

I believe this was fixed by @Alldar before too so credits for him to make try :)

**Comment by blesswinsamuel** [comment]
I have tried copying the contents of the entire file into administrator\templates\minima\css\template.css file, but I still have the same issue (I've also tried clearing the browser cache).

Also, I'd want JAT3 Clean Cache link to be displayed to the left side of Help button.

**Comment by marcobarbosa** [comment]
I'll reopen this until the next release, just to make sure it's fixed.

To display the "Clean Cache" beside the Help it would require some hacking..
You could try with your own CSS using absolute positioning (easiest way),

Hope this helps.

**Comment by marcobarbosa** [comment]
Hey Samuel, try updating Minima and let me know if it works.

**Comment by blesswinsamuel** [comment]
Thanks so much. Now they appear in correct positions.
